# Site settings
title: Red C Tech, LLC
email: williamsbdev@gmail.com
description: >
    Red C Tech, LLC offers software consulting.
baseurl: ""
url: "https://redctech.com"
twitter_username: redctech
github_username:  redctech

# Build settings
markdown: kramdown
