# Site settings
title: Red C Tech, LLC
email: williamsbdev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Red C Tech, LLC offers software consulting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://redctech.com"
twitter_username: redctech
github_username:  redctech

# Build settings
markdown: kramdown
